# Generated by Django 4.1.6 on 2023-02-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('nacionalidad', models.CharField(max_length=40))
            ]
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('equipo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('equipo', models.CharField(max_length=40)),
                                
            ],
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='nacionalidad',
        ),   
        migrations.RemoveField(
            model_name='equipo',
            name='equipo',
        )
    ]
